/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app/carro/Index': RouteRecordInfo<'/app/carro/Index', '/app/carro/Index', Record<never, never>, Record<never, never>>,
    '/app/configuracao/Index': RouteRecordInfo<'/app/configuracao/Index', '/app/configuracao/Index', Record<never, never>, Record<never, never>>,
    '/app/Index': RouteRecordInfo<'/app/Index', '/app/Index', Record<never, never>, Record<never, never>>,
    '/app/locacao/Index': RouteRecordInfo<'/app/locacao/Index', '/app/locacao/Index', Record<never, never>, Record<never, never>>,
    '/app/marca/Index': RouteRecordInfo<'/app/marca/Index', '/app/marca/Index', Record<never, never>, Record<never, never>>,
    '/app/modelo/Index': RouteRecordInfo<'/app/modelo/Index', '/app/modelo/Index', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/app/carro/Index.vue': {
      routes: '/app/carro/Index'
      views: never
    }
    'src/pages/app/configuracao/Index.vue': {
      routes: '/app/configuracao/Index'
      views: never
    }
    'src/pages/app/Index.vue': {
      routes: '/app/Index'
      views: never
    }
    'src/pages/app/locacao/Index.vue': {
      routes: '/app/locacao/Index'
      views: never
    }
    'src/pages/app/marca/Index.vue': {
      routes: '/app/marca/Index'
      views: never
    }
    'src/pages/app/modelo/Index.vue': {
      routes: '/app/modelo/Index'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
